const ACHIEVEMENT_STORAGE_KEY = 'citywalk_achievement_state';
const FEATURED_ACHIEVEMENT_STORAGE_KEY = 'citywalk_featured_achievement';
const ACHIEVEMENT_ASSETS = require('./achievement-assets');

const ACHIEVEMENTS = [
  {
    id: 'shape_master',
    title: '几何大师',
    description: '解锁形状漫步',
    progressLabel: '形状漫步',
    target: 1,
    type: 'boolean',
    asset: ACHIEVEMENT_ASSETS.shape_master,
    sort: 1,
  },
  {
    id: 'cat_marathon',
    title: '喵氏马拉松',
    description: '单次漫步里程 >= 5 公里',
    progressLabel: '单次里程',
    target: 5000,
    type: 'distance',
    milestones: [1000, 2000, 3000, 4000, 5000],
    asset: ACHIEVEMENT_ASSETS.cat_marathon,
    sort: 2,
  },
  {
    id: 'no_photo_five_walks',
    title: '我喵都不喵你',
    description: '5 次漫步未上传图片',
    progressLabel: '无图漫步',
    target: 5,
    type: 'count',
    asset: ACHIEVEMENT_ASSETS.no_photo_five_walks,
    sort: 3,
  },
  {
    id: 'ten_locations',
    title: '掌量世界',
    description: '在 10 个不同地点进行漫步',
    progressLabel: '不同地点',
    target: 10,
    type: 'count',
    asset: ACHIEVEMENT_ASSETS.ten_locations,
    sort: 4,
  },
  {
    id: 'spring_first_walk',
    title: '猫步探春',
    description: '解锁春季第一次漫步',
    progressLabel: '春',
    target: 1,
    type: 'season',
    season: '春',
    asset: ACHIEVEMENT_ASSETS.spring_first_walk,
    sort: 5,
  },
  {
    id: 'summer_first_walk',
    title: '猫步逐夏',
    description: '解锁夏季第一次漫步',
    progressLabel: '夏',
    target: 1,
    type: 'season',
    season: '夏',
    asset: ACHIEVEMENT_ASSETS.summer_first_walk,
    sort: 6,
  },
  {
    id: 'autumn_first_walk',
    title: '猫步踏秋',
    description: '解锁秋季第一次漫步',
    progressLabel: '秋',
    target: 1,
    type: 'season',
    season: '秋',
    asset: ACHIEVEMENT_ASSETS.autumn_first_walk,
    sort: 7,
  },
  {
    id: 'winter_first_walk',
    title: '猫步寻冬',
    description: '解锁冬季第一次漫步',
    progressLabel: '冬',
    target: 1,
    type: 'season',
    season: '冬',
    asset: ACHIEVEMENT_ASSETS.winter_first_walk,
    sort: 8,
  },
  {
    id: 'first_team_walk',
    title: '一起喵喵',
    description: '完成第一次同行漫步',
    progressLabel: '同行漫步',
    target: 1,
    type: 'boolean',
    asset: ACHIEVEMENT_ASSETS.first_team_walk,
    sort: 9,
  },
  {
    id: 'seven_day_streak',
    title: '圆满喵周',
    description: '连续 7 天坚持漫步',
    progressLabel: '连续天数',
    target: 7,
    type: 'count',
    asset: ACHIEVEMENT_ASSETS.seven_day_streak,
    sort: 10,
  },
  {
    id: 'lucky_can_drop',
    title: '开罐有奖',
    description: '每次完成漫步有 5% 概率掉落',
    progressLabel: '幸运掉落',
    target: 1,
    type: 'boolean',
    asset: ACHIEVEMENT_ASSETS.lucky_can_drop,
    sort: 11,
  },
  {
    id: 'first_color_walk',
    title: '给你点颜色喵',
    description: '完成第一次色彩漫步',
    progressLabel: '色彩漫步',
    target: 1,
    type: 'boolean',
    asset: ACHIEVEMENT_ASSETS.first_color_walk,
    sort: 12,
  },
];

module.exports = {
  ACHIEVEMENTS,
  ACHIEVEMENT_STORAGE_KEY,
  FEATURED_ACHIEVEMENT_STORAGE_KEY,
};
